version: '3'
services:
  db:
    image: postgres:11.11   # current prm version
#    image: postgres:12.8
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_USER: "lawsuits_user"
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "lawsuitsdb"
    ports:
      - 5432:5432
    restart: always
    volumes:                                                                    #init db from dump
       - ./dump2_prm_xdumpschema.sql:/docker-entrypoint-initdb.d/1-schema.sql   #init db from dump
       - ./dump2_prm_xdumpconfigdata.sql:/docker-entrypoint-initdb.d/2-data.sql #init db from dump
    stdin_open: true
    tty: true
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  lawsuits:
      image: lawsuits:latest
      ports:
        - 8080:8080
      environment:
        - SPRING_DATASOURCE_USERNAME=lawsuits_user
        - SPRING_DATASOURCE_PASSWORD=123
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/lawsuitsdb
